### ISSUE TITLE
Leaking virtualcollection listeners 

### ISSUE THREAD

**Issue by p3drosola** [p3drosola/Backbone.GroupedCollection#12]
- close_with option is not being passed to group_collection.closeWith
- close_with option is not being propagated to the virtualcollections, so they're leaking listeners

**Comment by masylum** [comment]
I can fix that one :)

**Comment by p3drosola** [comment]
Don't worry about it. https://github.com/p3drosola/Backbone.GroupedCollection/commit/39ea71a4d138218cdcf7ed3d69ef344b6cd71c32
