### ISSUE TITLE
Passing in filter as vc_options does not apply to grouped collection

### ISSUE THREAD

**Issue by snags88** [p3drosola/Backbone.GroupedCollection#16]
I have a scenario in which I want to create a grouped collection from a real collection, but also apply a filter at the same time. For example, given the following collection:
```javascript
var tasks = new Backbone.Collection([
  {name: 'bob', date: '02-19-2016', task: 'wash dishes'},
  {name: 'bob', date: '02-19-2016', task: 'read book'},
  {name: 'sally', date: '02-19-2016', task: 'walk the dog'},
  {name: 'bob', date: '02-20-2016', task: 'go to gym'},
]);
```
I want to only get Bob's tasks and group by date. Something like the following would be nice to do:
``` javascript
var groupedTasks = Backbone.buildGroupedCollection({
  collection: tasks,
  groupBy: function (task) {
    return task.get('date');
  },
  vc_options: {
    filter: function(task) {
      return task.get('name') === 'bob';
    }
  }
});
```
I looked around the code, and I think the reason why this doesn't work is because any filter options are overridden from [this code](https://github.com/p3drosola/Backbone.GroupedCollection/blob/master/backbone.grouped-collection.js#L84-L89). 

My current solution is to first create a virtual collection with the filter I want, then pass it in as the collection for the grouped collection:

``` javascript
var virtualCollection = Backbone.VirtualCollection(tasks, {
  filter: function(task) {
    return task.get('name') === 'bob';
  }
});

var groupedTasks = Backbone.buildGroupedCollection({
  collection: virtualCollection,
  groupBy: function (task) {
    return task.get('date');
  }
});
```

Going to play around with this over the weekend, but figured I should raise an issue in case others are running into this.

**Comment by p3drosola** [comment]
I think the best way is what you're doing already. the groupBy function needs to return a group name for every element, what would group would elements you want to skip pertain to? 

I prefer not to add more complexity, to achieve what can already be done.

**Comment by snags88** [comment]
the elements to skip/filtered out would not belong in any group so it would not be part of any virtual collection of the resulting models. It just feels weird to create a filtered virtual collection, then pass it into a grouped collection which uses virtual collections in the implementation.

On a different note, I understand not adding more complexity. I'll still play around with it since we're using grouped collections on a project. I'll keep you posted on a solution I come up with
